### ISSUE TITLE
Localization Translations

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4projects/website2#4]
Localization prep is complete, and my students will be handling some of the locale translations over the next few weeks.

**Comment by jim-parry** [comment]
Locales spoken for: en-ca, fr, ja, vn, zn-ch.
These may not result in complete translations, especially while the work is in process. 
Target completion: Oct 21, 2019.

**Comment by jim-parry** [comment]
The student projects have completed. Not all of the translation sets are complete. Missing:
- fr/Downloads
- ja/ all but 2
- vn/ half
- zh-CN  four of them

I am going to disable Japanese, Vietnamese & Simplified Chinese until they are more complete (if that happens).
I will keep French - it is complete enough to be useful.

Two of the larger community members also stepped up, with translation sets for Brazilian and RUssian :D

**Comment by lonnieezell** [comment]
Since the school is no longer involved with the project, we have made the decision to remove localization.
