### ISSUE TITLE
Website only shows an error message 

### ISSUE THREAD

**Issue by vaibhavbshete** [codeigniter4projects/website2#53]
Currently the website at https://codeigniter.com/ only shows:

**### Whoops!**

We seem to have hit a snag. Please try again later...

user_guide works fine. But there is no link on the main site for a new user to know what is going on. Just an error message.

**Comment by LittleJ** [comment]
@lonnieezell

**Comment by LittleJ** [comment]
https://forum.codeigniter.com/thread-75851.html

**Comment by michalsn** [comment]
Please follow #57 for answers.
