### ISSUE TITLE
bootstrap.php not found. 

### ISSUE THREAD

**Issue by abualk** [codeigniter4projects/website2#56]
I downloaded this amazing script that I was looking for long time. when I installed the script I got this error message. 

`Warning: require(/Applications/XAMPP/xamppfiles/htdocs/CI/app/Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/CI/public/index.php on line 36`

moreover, I'm trying to move the index.php file out of the public, 
with both cases(having index in public/main root), I'm getting same error. I wonder how to fix this ? 

thank you so much

**Comment by LittleJ** [comment]
Hello ! This is probably not the good place to post your questions. This is a special repo for Codeigniter's official website. Please use the forum instead: https://forum.codeigniter.com/
You will get answers from experts that will be happy to assist you with your problem.
Thank you !

**Comment by abualk** [comment]
thank you LittleJ, 
the thing I managed to installed CI4 successfully. yet this is related this respo. I downloaded it and try to run it on localhost, didn't work. 

thank you

**Comment by LittleJ** [comment]
This repo is CI's website. This: https://codeigniter.com/
Probably not what you are looking for. What are you looking for ?

**Comment by abualk** [comment]
I am thinking this is a bug in the repo . I'm trying to install this on my localhost and I got this message. this is why I'm posting my question here. 


 if you can guide me how to get this fixed :) 

million thanks,

**Comment by LittleJ** [comment]
Is your goal to modify CI's website itself ?

**Comment by abualk** [comment]
not at all, I'm thinking to install it to local host, and try to run it. later, I will add some features. yet it's not working as is

**Comment by LittleJ** [comment]
Yes, but do you want to add features to CodeIgniter (the framework) or CodeIgniter's website (the place where people get info about CI) ?

**Comment by LittleJ** [comment]
I need to know to answer

**Comment by abualk** [comment]
I would love this to work on my localhost first . and honestly speaking, I dont get your question. I like this modified script because mainly, I'm looking for language switcher. yet when I found this repo, it has way more than what I asked for, Bootstrap styling, forum running and it suits me well. so I want to start from there. 

I am not good programmer so I just want to start learning and add things time by time.

**Comment by LittleJ** [comment]
This repo is to install locally the website, not the framework. That's why I'm asking. If you are looking for the framework, this is NOT the right repo/place.

**Comment by abualk** [comment]
so you are suggesting to install the framework itself and copy the files (replace) them?

**Comment by LittleJ** [comment]
I am saying those are different things. This is not the framework. This is not Codeigniter. This is the website to present Codeigniter. So I am asking if you want to modify the website, or if you want to work on the framework :-)

**Comment by abualk** [comment]
I'm truly sorry for my silly questions. I managed to work this out :) 

yet now I'm getting:
APPPATH/Libraries/GithubAPI.php at line 28
and I assume the problem is with the $systemDirectory  variable 
 so in paths.php
I changed it to : 
	public $systemDirectory = __DIR__ . '/../../system';
from:
	public $systemDirectory = __DIR__ . '/../../system';


and I'm getting this: `APPPATH/Libraries/GithubAPI.php at line 28
28         $this->client = new Github\Client(

`

I'm getting one step closer thanks to you :)

**Comment by LittleJ** [comment]
I am not sure of what you are doing. And I am currently in the team working on the website. I did not have to modify anything or do this kind of manipulations.

Maybe you should ask your questions on the forum as suggested (best place for it).

@lonnieezell Maybe my english is not good enough to make myself understand, if you want to add something, please don't hesitate :-D

**Comment by abualk** [comment]
not at all, it's just me who dont understand how this works, if you can just help me to have full script along with the CI script , that would the so generous from your side :)

**Comment by LittleJ** [comment]
I can help you. I am one of the contributors to the framework. But, to help you, i need to know what is your goal. This means:
1/ What are you trying to install. Codeigniter or the website that presents Codeigniter ?
2/ What do you want to do at the end ? Do you want to create an app ? Or help develop Codeigniter ?

Tell me what is your goal. What are you trying to do with all this. What is the final result you expect. What do you want to work on.

**Comment by LittleJ** [comment]
Because right now you are trying to setup the website. Which is just... a website. The official website.

**Comment by lonnieezell** [comment]
Additionally, it looks like you already have a [forum thread](https://forum.codeigniter.com/thread-76184.html) about this and are getting help there. Let's take this convo there since it looks like jkrelund has given you good advice.

**Comment by abualk** [comment]
I'm really grateful for your help. I'm trying to install codeingiter on localhost with your respo. as I'm trying to create an app :)
