### ISSUE TITLE
Can't run site

### ISSUE THREAD

**Issue by PwrSrg** [codeigniter4projects/website2#57]
Either there is something messed up with this repo, or I am doing something completely wrong.

I have been trying to get this running on my local machine for a few days now, and all I can ever get
is a "Whoops!" error message.  I have tried many different methods on two different machines.

**Here is how to reproduce the issue:**
```
git clone https://github.com/codeigniter4projects/website2
cd website2
composer install
composer update
php spark serve
http://localhost:8080

Whoops!
```

**Here is what shows up in the Log File:**
CRITICAL - 2020-07-07 22:57:03 --> Request URI segment is our of range: 1
#0 C:\Users\SergiHome\www\website2\vendor\codeigniter4\framework\system\HTTP\URI.php(485): CodeIgniter\HTTP\Exceptions\HTTPException::forURISegmentOutOfRange(1)
#1 C:\Users\SergiHome\www\website2\app\Controllers\BaseController.php(67): CodeIgniter\HTTP\URI->getSegment(1)
#2 C:\Users\SergiHome\www\website2\app\Controllers\Home.php(99): App\Controllers\BaseController->render('welcome')
#3 C:\Users\SergiHome\www\website2\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Home->index()
#4 C:\Users\SergiHome\www\website2\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\Users\SergiHome\www\website2\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\SergiHome\www\website2\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\Users\SergiHome\www\website2\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\Users\\SergiH...')
#8 {main}

**What am I missing???**

**Comment by lonnieezell** [comment]
What version of PHP are you running? Is it at least 7.2?

**Comment by lonnieezell** [comment]
Ah - found  the missing steps.

- copy `env` to `.env`
- change the following lines: 

```
CI_ENVIRONMENT = development
MOCK_MYBB = true
```

The environment line will show errors, etc. The MOCK_MYBB will not try to connect to an existing MyBB installation, which is probably what you need for local development. 

This all works for me on PHP 7.2.

**Comment by PwrSrg** [comment]
I had tried that too, but I basically get the same error, just without the "Whoops!".

```
CodeIgniter\HTTP\Exceptions\HTTPException
Request URI segment is our of range: 1
```
PHP 7.3.11

[ci4 website2 error 01.zip](https://github.com/codeigniter4projects/website2/files/4900095/ci4.website2.error.01.zip)

**Comment by lonnieezell** [comment]
Strange. When I ran it I was using the built in `php spark serve`. Are you using it under Apache or something else? If so, you might try using the built-in server.

**Comment by PwrSrg** [comment]
Yes, as originally stated, I am using `php spark serve`.
Here is a video of the entire process from start to finish:

https://youtu.be/bEKpvSs5hlc

**Comment by lonnieezell** [comment]
Sorry forgot that. Unfortunately I don't have an answer. And I don't have a Windows dev box up and running currently so I cannot recreate it. Any help you could give by debugging it would be helpful, though. 

I would guess a first step might be to try using different values for `$uriProtocol` to see if that changes anything. Changing it to PATH_INFO might help? Taking a stab in the dark here. Sorry.

**Comment by michalsn** [comment]
`Controllers\BaseController::render()` - adding `$this->request->uri->setSilent()` in the first line should fix it.
